; ============================================================
;  ESP32-C3 Smartwatch + Navigation
;  Display : 1.54" TFT ST7789 240x240 SPI
;  UI      : LVGL 8.3 + TFT_eSPI
;  Build   : PlatformIO
; ============================================================
[env:esp32-c3-devkitm-1]
platform      = espressif32
board         = esp32-c3-devkitm-1
framework     = arduino
monitor_speed = 115200
upload_speed  = 921600

; LittleFS cho wallpaper + cau hinh
board_build.filesystem = littlefs
; App lon (BLE+WiFi+LVGL ~1.45MB) -> dung partition huge_app (3MB app, khong OTA)
board_build.partitions = huge_app.csv

lib_deps =
    lvgl/lvgl@^8.3.11
    lovyan03/LovyanGFX@^1.1.16
    bblanchon/ArduinoJson@^7.0.4
    h2zero/NimBLE-Arduino@^1.4.1

build_flags =
    ; ---- LVGL: tro toi lv_conf.h trong src/ ----
    -I src
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_LVGL_H_INCLUDE_SIMPLE

    ; ---- Man hinh cau hinh bang code (LGFX class trong display.cpp), khong can build flag ----

    ; ---- App cua minh ----
    -D CORE_DEBUG_LEVEL=1
    -std=gnu++17

build_unflags =
    -std=gnu++11
