name: vhi_watch
description: App Android dieu khien dong ho thong minh ESP32-C3 (BLE + chi duong + doi anh nen)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_blue_plus: ^2.3.9        # BLE (ban 2.x da sua loi gradle compileSdk)
  permission_handler: ^11.3.1     # xin quyen runtime
  image: ^4.2.0                   # resize + convert RGB565
  image_picker: ^1.1.2            # chon anh tu thu vien
  notification_listener_service: ^1.0.0  # doc thong bao Android

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
